### ISSUE TITLE
Após altera a movimentação da DAMA ah um erro no console

### ISSUE THREAD

**Issue by B0yEditi0n** [B0yEditi0n/DamaPublicTreino#1]
### Mensagem de erro
script.js:263  Uncaught TypeError: Cannot read properties of undefined (reading '2')
    at Object.isValidPlacetoMove (script.js:263:26)
    at Piece.canOpponentJump (script.js:108:18)
    at Piece.canJumpAny (script.js:76:23)
    at HTMLDivElement.<anonymous> (script.js:395:23)
    at HTMLDivElement.dispatch (jquery-3.3.1.slim.min.js:2:41964)
    at v.handle (jquery-3.3.1.slim.min.js:2:39983)
### previw do Código
```
isValidPlacetoMove: function (row, column) {
      console.log(row); console.log(column); console.log(this.board);
      if (row < 0 || row > 7 || column < 0 || column > 7) return false;
      if (this.board[row][column] == 0) {
        return true;
      }
      return false;
},
```

**Comment by B0yEditi0n** [comment]
tente usar um try e na except use um debugger

**Comment by B0yEditi0n** [comment]
achei o BO, por estender a dama ele divide o a posição atual pela final, e tenta ver se tem algum peça no meio.
como a dama pode pular mais de uma casa a divisão sai quebrada
